### ISSUE TITLE
no but, repetitive phrase, almost repetitive sentences. 

### ISSUE THREAD

**Issue by Vlevo** [DragonRidersUnite/book#10]
03-spit-fire.md

61 "We use arrays to represent various data in our game like labels and sprites, but we can create our own arrays to keep track of the data in our game. Arrays are a great way to collect data that we then use throughout our game. In this case, we're maintaining a collection of fireballs."

There is no "negation" of the first part of the sentence, so there should be no ", but". How should it get fixed? is it an "and"? or a new sentence? (". We can [also] create [...] of our data.")

Same/similar phrase in three back-to-back "sentences": "data in our game", "data in our game", and "data [...] throughout our game"

The latter two of those "sentences" are almost, but not quite, saying the same thing.

(The last sentence ("In this case...") is included solely to complete the context/paragraph.")

**Comment by brettchalupa** [comment]
@Vlevo thanks for this feedback! I reworded that paragraph to be less awkward.
