### ISSUE TITLE
Verbiage 'source-control.md' line 106

### ISSUE THREAD

**Issue by Vlevo** [DragonRidersUnite/book#23]
This paragraph is talking about the engine, so "sync that" is suggesting that we open-source the engine, even though you've just been telling us how not to...

106  The downside to this approach is that you need to ensure you keep your specific engine version parent directory available. You could use version control to sync that and then use Git to publish it online as open-source code.

**Comment by brettchalupa** [comment]
Good call out, @Vlevo! I tried to make it better. 👍
