### ISSUE TITLE
Dead/incorrect links

### ISSUE THREAD

**Issue by esmale** [DragonRidersUnite/book#33]
* The link to the "Code the Classics" book in the "Game Dev Resources" section redirects to https://filmstories.co.uk/news/, which has no content related to this book.  I can find a variety of links to purchase the book via google, but the current link on this page appears to be dead.

* In the Animation chapter, there's a link for this text: "[The DragonRuby GTK docs have a detailed example of how to do this.](http://docs.dragonruby.org/#----animation-using-sprite-sheet---main-rb)". That link is incorrect and lands you on a "404 - not found" page within the DragonRuby docs.  I think that page that should actually be linked to should be: https://docs.dragonruby.org/#/samples/rendering-sprites?id=animation-using-sprite-sheet-mainrb

**Comment by brettchalupa** [comment]
@esmale thanks for reporting these issues, will work on fixing them!

**Comment by brettchalupa** [comment]
Bullet 2 was fixed in https://github.com/DragonRidersUnite/book/pull/34, submitting a PR to fix bullet 1
