### ISSUE TITLE
Epub version

### ISSUE THREAD

**Issue by hoblin** [DragonRidersUnite/book#35]
It would be awesome to have a native version for iOS devices/macOS.

**Comment by brettchalupa** [comment]
Thanks for the suggestion, I think it'd be great too! The book is built with open source software called mdBook, and there's some info on how this could be possible (although experimental):

- https://github.com/Michael-F-Bryan/mdbook-epub
- https://github.com/rust-lang/mdBook/issues/815#issuecomment-1868345167
- https://github.com/max-heller/mdbook-pandoc
- https://github.com/crowdagger/crowbook

I have some personal interest in revising the book to make sure it works with the latest DRGTK version and possibly expand it with some more content. So let's keep this issue open to track the idea for epub version.

**Comment by brettchalupa** [comment]
@hoblin here's an epub version generated with mdbook-epub:

[Building Games with DragonRuby.epub.zip](https://github.com/user-attachments/files/18001444/Building.Games.with.DragonRuby.epub.zip)

Give it a try and let me know what you think. Let's not call it officially supported, but it's something at least. Was easy to do, but might not have the best formatting or experience. Here's the Git branch: https://github.com/DragonRidersUnite/book/tree/epub

**Comment by hoblin** [comment]
So far, it looks ok. Code blocks lack syntax highlighting, but it is better than nothing 
Light theme:
![image](https://github.com/user-attachments/assets/50a17211-fd34-4939-afbd-5fdc57afc661)
Dark theme:
![image](https://github.com/user-attachments/assets/a10e470c-a9b5-4156-8f02-91eb627ffcf8)
