### ISSUE TITLE
#name ...

### ISSUE THREAD

**Issue by Vlevo** [DragonRidersUnite/book#8]
Seeing that your chap3 explanation of `#tick` is a nice simple: `(#name is Ruby shorthand for "the name method")`. I believe that it could possibly be moved to chap2, as that use is: `In #tick we'll check [...]`.

The `#greet` in chap1 still needs removing (it is redundant, `the 'greet method' method` and immediately above `def greet friend`.)

It might seem cool to move the explanation to chapter one, but that is a tighter space to try and shoehorn it into and you should probably say "the name method" a few more times before that combo starts to vanish. There are a nice number of them in this chapter (before and after "the `#greet` method". (low, it would probably be best to keep this chapter `#`-less.) In chap2 there are two uses of "____ method", both of which precede the `#tick` in question.

In chap3 there is also a redundant `#tick method` ("the tick method method", kind of like "a NIC card" (Network Interface Card card) but not as funny, since with "#tick method" the second method is unnecessary.) 

---- 
_(chapter#, current text, possibilities.)_

-chap1:
Go ahead and change the `#greet` method to:

Go ahead and change the `greet` method to:

-chap2:
In `#tick` we'll check to see if a given input is pressed.

In the `tick` method we'll check to see if a given input is pressed.

In `#tick` (`#name` is Ruby shorthand for "the `name` method") we'll check to see if a given input is pressed.

-chap3:
In our `#tick` method, right above where we render the dragon sprite,

In our `tick` method, right above where we render the dragon sprite,

In `#tick`, right above where we render the dragon sprite,

-chap3:
At the top of `#tick` (`#name` is Ruby shorthand for "the `name` method"), assign an empty array to

At the top of `#tick` assign an empty array to

**Comment by brettchalupa** [comment]
@Vlevo thanks for logging this and being so thorough with it! I'll work on improving it for v1.1.
